exclude: '\.ipynb$'
repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        args: ['--in-place', '--ignore=E402']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(cdk)/tests/unit/snapshots
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4', '--no-ensure-ascii', '--skip-string-normalization']
        exclude: ^(cdk)/tests/unit/snapshots
      - id: check-yaml
