import urllib.parse
from igvf_client import Configuration
from igvf_client import ApiClient
from igvf_client import IgvfApi
import os
import pandas as pd
import itertools
import urllib
from datetime import datetime

# TODO: Add proper docstring

def get_igvf_auth_and_api(igvf_site: str = 'production'):
    """Set up IGVF data portal access and set up IGVF python client api.
    """
    if igvf_site == 'production':
        host = 'https://api.data.igvf.org'
    elif igvf_site == 'sandbox':
        host = 'https://api.sandbox.igvf.org'
    config = Configuration(
        access_key=os.environ["IGVF_API_KEY"],
        secret_access_key=os.environ["IGVF_SECRET_KEY"],
        host=host
    )
    client = ApiClient(config)
    return IgvfApi(client)


#  HACK: A map that translates an assay term to either ATAC or RNA
# assay_terms_map = {
#     '/assay-terms/OBI_0003109/': 'rna',
#     '/assay-terms/OBI_0002762/': 'atac',
#     '/assay-terms/OBI_0002764/': 'atac',
#     '/assay-terms/OBI_0002631/': 'rna',
#     '/assay-terms/OBI_0003090/': 'rna',     # For test analysis set only
#     '/assay-terms/OBI_0003089/': 'atac'     # For test analysis set only
# }

# HACK: A map that uses platform_preferred-assay-title_assay-type to inference read map for pipelines.
read_type_by_platform_map = {
    '/platform-terms/EFO_0008637/_SHARE-seq_atac': {'R1': 'read1', 'R2': 'read2'},
    '/platform-terms/EFO_0008637/_SHARE-seq_rna': {'R1': 'read1', 'R2': "read2"},
    '/platform-terms/EFO_0022840/_10x multiome with MULTI-seq_atac': {'R1': 'read1', 'R3': 'read2'},
    '/platform-terms/EFO_0022840/_10x multiome with MULTI-seq_rna': {'R1': 'read1', 'R2': 'read2'},
    '/platform-terms/EFO_0008637/_RNA-seq_rna': {'R1': 'read1', 'R2': 'read2'},     # For test analysis set only
    '/platform-terms/EFO_0010963/_ATAC-seq_atac': {'R1': 'read1', 'R2': 'read2'},    # For test analysis set only
    '/platform-terms/NTR_0000765/_10x multiome with MULTI-seq_rna': {'R1': 'read1', 'R2': 'read2'},
    '/platform-terms/NTR_0000765/_10x multiome with MULTI-seq_atac': {'R1': 'read1', 'R3': 'read2'},
    '/platform-terms/EFO_0010963/_Parse SPLiT-seq_rna': {'R1': 'read1', 'R2': 'read2'}
}


def get_assay_type_from_assay_id(assay_term_id: str, igvf_api) -> str:
    # NOTE: This may get more complicated if the pipeline wants to distinguish sn vs. sc
    """Infer assay type (RNA or ATAC) from the assay term summary

    Args:
        assay_term_id (str): assay term id
        igvf_api (_type_): _description_

    Returns:
        str: rna or atac
    """
    assay_term_summary = igvf_api.get_by_id(assay_term_id).actual_instance.summary
    if 'RNA' in assay_term_summary:
        return 'rna'
    elif 'ATAC' in assay_term_summary:
        return 'atac'


def get_samp_taxa_from_samp_id(sample_id: str, igvf_api) -> str:
    """Get sample taxa from a sample ID

    Args:
        sample_id (str): e.g., /in-vitro-system/IGVFxxxxx
        igvf_api (_type_): _description_

    Returns:
        str: e.g., Homo sapiens
    """
    sample_item = igvf_api.get_by_id(sample_id).actual_instance
    return sample_item.taxa


def get_measet_ids_and_taxa_from_analysis_set_acc(analysis_set_accessions: list, igvf_api) -> tuple:
    """Get all input measurement set IDs and sample taxa from an analysis set.

    Args:
        analysis_set_accessions (list): A list of one analysis set accession
        igvf_api (_type_): _description_

    Returns:
        tuple: (list(taxa), list(measurement ids))
    """
    analysis_set_objs = igvf_api.analysis_sets(accession=analysis_set_accessions).graph[0]
    measurement_ids = [measet_id for measet_id in analysis_set_objs.input_file_sets if 'measurement-sets' in measet_id]
    sample_taxa = list(set([get_samp_taxa_from_samp_id(sample_id=samp_id, igvf_api=igvf_api) for samp_id in analysis_set_objs.samples]))
    return (sample_taxa, measurement_ids)


def get_and_sort_measurement_sets_by_assays(measurement_set_ids: list, igvf_api) -> list:
    """Sort a list of measurement set items based on assay terms.

    Args:
        measurement_set_ids (list): A list of measurement set items generated by the APi.
        igvf_api (_type_): _description_

    Returns:
        list: Same content as the input list but sorted by the assay terms.
    """
    return sorted([igvf_api.get_by_id(measet_id).actual_instance for measet_id in measurement_set_ids], key=lambda x: x.assay_term)


def get_seqfiles_by_assays_and_pref_titles(measet_items: list, igvf_api) -> tuple:
    """Get sequence file items and the preferred assay title.

    Args:
        measet_items (list): A list of measurement set items sorted by assay terms.
        igvf_api (_type_): _description_

    Returns:
        tuple: ([sequence file items], preferred_assay_title, [seqfile measurement accessions])
    """
    file_items = []
    # Get preferred assay title which will tell if it is atac or rna
    preferred_assay_title = set()
    # For each measurement set of the same assay type, look for seqfiles
    measet_accs = []
    for measet_item in measet_items:
        preferred_assay_title.add(measet_item.preferred_assay_title)
        measet_accs.append(measet_item.accession)
        for file in measet_item.files:
            if 'sequence-files' in file:
                file_items.append(igvf_api.get_by_id(file).actual_instance)
    preferred_assay_title = list(preferred_assay_title)[0]    # Should be only 1 but just to be sure
    return (file_items, preferred_assay_title, measet_accs)


def seqfile_sort_func(x):
    """Set up sorting sorter for sequence file item lists.
    """
    return (x.file_set, x.illumina_read_type, x.sequencing_run, x.lane)


def get_seqfile_seqinfo(seqfile_item, preferred_assay_title: str, assay_type: str) -> str:
    """HACK: Use sequence file metadata to infer FASTQ file read types.

    Args:
        seqfile_item (_type_): Return item from the API
        preferred_assay_title (str): _description_
        assay_type (str): translated from assay term into atac or rna

    Returns:
        str: e.g., atac_read1, rna_read2
    """
    read_type_key = '_'.join([seqfile_item.sequencing_platform, preferred_assay_title, assay_type])
    if seqfile_item.illumina_read_type in list(read_type_by_platform_map[read_type_key].keys()):
        read_file_title = '_'.join([assay_type, read_type_by_platform_map[read_type_key][seqfile_item.illumina_read_type]])
        return read_file_title


def get_seqspec(seqspec_ids: list, igvf_api) -> tuple:
    """_summary_

    Args:
        seqspec_ids (list): _description_
        igvf_api (_type_): _description_

    Returns:
        tuple: _description_
    """
    seqspec_accessions = set()
    seqspec_urls = set()
    for seqspec_id in seqspec_ids:
        curr_seqspec_item = igvf_api.get_by_id(seqspec_id).actual_instance
        seqspec_accessions.add(curr_seqspec_item.accession)
        seqspec_urls.add(urllib.parse.urljoin('https://api.data.igvf.org', curr_seqspec_item.href))
    return (seqspec_accessions, seqspec_urls)


class SingleCellInputBuilder:
    def __init__(self, analysis_set_acc: str, igvf_api):
        self.data = {'analysis_set_acc': '',
                     'atac_MeaSetIDs': [],
                     'rna_MeaSetIDs': [],
                     'taxa': [],
                     'atac_read1_accessions': [],
                     'atac_read2_accessions': [],
                     'rna_read1_accessions': [],
                     'rna_read2_accessions': [],
                     'seqspec_accessions': set(),  # TODO: Need to add seqspec
                     'atac_read1': [],
                     'atac_read2': [],
                     'rna_read1': [],
                     'rna_read2': [],
                     'seqspec_urls': set()  # TODO: Need to add seqspec
                     }
        self.analysis_set_acc = analysis_set_acc
        self.igvf_api = igvf_api
        self.samp_taxa, self.measet_ids = get_measet_ids_and_taxa_from_analysis_set_acc(analysis_set_accessions=self.analysis_set_acc, igvf_api=self.igvf_api)

    def get_seqfile_uris_and_seqspec_by_assays_and_runs(self):
        """Get s3 uri of sequence files and add to the report dict based on their assay type and read types.
        """
        # Get a list of measurement set items sorted by the assay terms.
        measets_sorted_by_assays = get_and_sort_measurement_sets_by_assays(measurement_set_ids=self.measet_ids, igvf_api=self.igvf_api)
        for assay_grp, measet_items in itertools.groupby(measets_sorted_by_assays, key=lambda x: x.assay_term):
            # Get a list of seqfile items, preferred assay title, and linked measurement set accessions.
            seqfile_items, preferred_assay_title, assay_measet_accs = get_seqfiles_by_assays_and_pref_titles(measet_items=measet_items, igvf_api=self.igvf_api)
            # Infer assay type
            assay_type = get_assay_type_from_assay_id(assay_term_id=assay_grp, igvf_api=self.igvf_api)
            # Add the linked measurement set accessions to the report dict
            self.data[f'{assay_type}_MeaSetIDs'].extend(assay_measet_accs)
            # Sort the list of seqfile items by file set acc, illumina read type, run, and lane if present, then
            # get S3 URIs and file accessions.
            for seqfile_item in sorted(seqfile_items, key=seqfile_sort_func):
                # HACK: Check if something is R read type or I read type
                if seqfile_item.illumina_read_type.startswith('R'):
                    read_file_title = get_seqfile_seqinfo(seqfile_item=seqfile_item, preferred_assay_title=preferred_assay_title, assay_type=assay_type)
                    # HACK: If the read_file_title is blank (e.g., R1 and R3, but not R2), skip
                    if read_file_title is not None:
                        self.data[f'{read_file_title}_accessions'].append(seqfile_item.accession)
                        self.data[read_file_title].append(urllib.parse.urljoin('https://api.data.igvf.org', seqfile_item.href))
                        # Also grab seqspec info
                        # TODO: This will fail as most seqfiles don't have a correct one linked via seqspecs
                        seqspec_accs, seqspec_urls = get_seqspec(seqspec_ids=seqfile_item.seqspecs, igvf_api=self.igvf_api)
                        self.data['seqspec_accessions'].update(seqspec_accs)
                        self.data['seqspec_urls'].update(seqspec_urls)

    def build_input_dict(self) -> dict:
        """Build the final output report dict
        """
        self.data['analysis_set_acc'] = ','.join(self.analysis_set_acc)     # Technically it is a list of one
        self.data['taxa'] = self.samp_taxa
        # Get seqfile URLs
        self.get_seqfile_uris_and_seqspec_by_assays_and_runs()
        # Make unique seqspec list
        self.data['seqspec_accessions'] = list(self.data['seqspec_accessions'])
        self.data['seqspec_urls'] = list(self.data['seqspec_urls'])
        return self.data


def main(query_analysis_set_accs: list, igvf_api, save_to_file: bool = False, output_path='./') -> pd.DataFrame:
    """Full script to go from a query measurement set accession to a uniform pipeline input TSV.

    Args:
        query_measet_accs (list): A list of MeaSet accessions for the uniform pipeline
        igvf_api (_type_): _description_
        save_to_file (bool, optional): Defaults to pipeline_input_table.
        output_path (str, optional): Defaults to './'.

    Returns:
        pd.DataFrame: Final uniform pipeline input tsv.
    """
    pipeline_input_list = []
    for anaset_acc in query_analysis_set_accs:
        # curr_samp_id = get_samp_ids_from_measets(measurement_set_accessions=[measet_acc], igvf_api=igvf_api)
        curr_input_builder = SingleCellInputBuilder(analysis_set_acc=[anaset_acc], igvf_api=igvf_api)
        pipeline_input_list.append(curr_input_builder.build_input_dict())
    pipeline_input_table = pd.DataFrame(pipeline_input_list)
    # Output TSV if needed
    if save_to_file:
        curr_datetime = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        pipeline_input_table.to_csv(os.path.join(output_path, f'single-cell_uniform_pipeline_input_table_{curr_datetime}.tsv'), sep="\t")
    else:
        return pipeline_input_table


if __name__ == '__main__':
    # Tester measurement set
    nonmultiplexed_measets = ['IGVFDS0020LQRY', 'IGVFDS7133CHRI']
    multiplexed_measets = ['IGVFDS5205JRNX', 'IGVFDS3910GBDQ']
    analysis_sets = ['IGVFDS0006MFFD', 'IGVFDS9202ZPBI']
    main(query_analysis_set_accs=analysis_sets,
         igvf_api=get_igvf_auth_and_api(),
         save_to_file=True,
         output_path='/Users/zheweishen/IGVF/single_cell_fg/Portal_input_output/test_input'
         )
